### ISSUE TITLE
Inconsistent behaviour when removing nodes

### ISSUE THREAD

**Issue by jsbezerra** [Verites/verigraph#20]
The function `removeNodeFromDomain` from the `GraphMorphism` module does not remove a node that has incident edges, which is the default behaviour of verigraph in order to not generate invalid structures. 

However, it still removes the mapping of the node to its image, which may lead to invalid graphs.

**Comment by lm-rodrigues** [comment]
The function `removeNodeFromCodomain` has the same behaviour, I will fix this issue on `master` and on version `1.0`.
