### ISSUE TITLE
Migrate all tests to default approach

### ISSUE THREAD

**Issue by ggazzi** [Verites/verigraph#22]
Currently, some of the tests are using plain HUnit and some are using Hspec with HUnit and QuickCheck. We should unify all tests under a single style.

**Comment by ggazzi** [comment]
My suggestion is to adopt Hspec and hspec-discover. Then we could have a single `test-suite` entry in `verigraph.cabal`.

**Comment by lm-rodrigues** [comment]
A single `test-suite`  entry on cabal file will also simplify the coverage report to coveralls.io

**Comment by ggazzi** [comment]
An approach was chosen and document on [the wiki](https://github.com/Verites/verigraph/wiki/Unit-Testing-Practices). The minimal configuration was introduced in commit e308a51.

At some point we should migrate all tests to the new approach.

**Comment by lm-rodrigues** [comment]
With changes introduced on 699b0911166ec0d957dd5382e98139254d58e0be all tests are implemented with the new approach.
