### ISSUE TITLE
Fix "HLint/UseFewerImports" issue in src/Main.hs

### ISSUE THREAD

**Issue by lm-rodrigues** [Verites/verigraph#31]
Use fewer imports

https://codeclimate.com/github/Verites/verigraph/src/Main.hs#issue_5915dea832268a00010000ab

**Comment by jsbezerra** [comment]
A better solution is to delete the src/Main.hs file. This file is not used by the project anymore and it is full of old code for ad-hoc tests from before the test suites creation.
