### ISSUE TITLE
Fix "TODO / FIXME" issue in src/library/Abstract/EpiPairs.hs

### ISSUE THREAD

**Issue by lm-rodrigues** [Verites/verigraph#36]
TODO / FIXME found

https://codeclimate.com/github/Verites/verigraph/src/library/Abstract/EpiPairs.hs#issue_5915ed1aabd07f00010000b1

**Comment by andreicosta** [comment]
Fixed in [20cebef](https://github.com/Verites/verigraph/commit/20cebef251d09a1aee2849f53390ce9d520319cf)
