### ISSUE TITLE
Fix "TODO" issue in src/library/Analysis/CriticalSequence.hs

### ISSUE THREAD

**Issue by lm-rodrigues** [Verites/verigraph#39]
TODO found

https://codeclimate.com/github/Verites/verigraph/src/library/Analysis/CriticalSequence.hs#issue_5915ed1aabd07f00010000ad

**Comment by andreicosta** [comment]
FIxed in [7893aeb](https://github.com/Verites/verigraph/commit/7893aeb119d8fb82d3863b3bdce4b09cf27ee95c)
